import type Database from 'better-sqlite3'
import type { FieldDefinition } from '@shared/types'

interface MediaTypeSeed {
  key: string
  label: string
  icon: string
  color: string
  fields_schema: FieldDefinition[]
  sort_order: number
}

const builtinMediaTypes: MediaTypeSeed[] = [
  {
    key: 'books',
    label: 'Books',
    icon: '\uD83D\uDCDA',
    color: '#4F7942',
    sort_order: 1,
    fields_schema: [
      { key: 'author', label: 'Author', type: 'combobox' },
      {
        key: 'genre',
        label: 'Genre',
        type: 'select',
        options: [
          'Fiction',
          'Non-Fiction',
          'Science Fiction',
          'Fantasy',
          'Mystery',
          'Thriller',
          'Romance',
          'Horror',
          'Historical Fiction',
          'Biography',
          'Memoir',
          'Self-Help',
          'Science',
          'Philosophy',
          'Poetry',
          'Young Adult',
          "Children's",
          'Business',
          'True Crime',
          'Graphic Novel',
          'Literary Fiction',
          'Classics',
        ],
      },
      {
        key: 'sub_genre',
        label: 'Sub-Genre',
        type: 'select',
        options: [
          'Epic Fantasy',
          'Urban Fantasy',
          'Dark Fantasy',
          'Space Opera',
          'Cyberpunk',
          'Dystopian',
          'Cozy Mystery',
          'Police Procedural',
          'Legal Thriller',
          'Psychological Thriller',
          'Contemporary Romance',
          'Historical Romance',
          'Paranormal Romance',
          'Gothic Horror',
          'Cosmic Horror',
          'Coming of Age',
          'Satire',
          'Magical Realism',
          'Military Sci-Fi',
          'Steampunk',
          'Hard Sci-Fi',
        ],
      },
      {
        key: 'format',
        label: 'Format',
        type: 'select',
        options: ['Hardcover', 'Paperback', 'eBook', 'Audiobook'],
      },
      { key: 'pages', label: 'Pages', type: 'number' },
      { key: 'isbn', label: 'ISBN', type: 'text' },
      { key: 'publisher', label: 'Publisher', type: 'combobox' },
      { key: 'year_published', label: 'Year Published', type: 'number' },
    ],
  },
  {
    key: 'music',
    label: 'Music',
    icon: '\uD83C\uDFB5',
    color: '#8B5CF6',
    sort_order: 2,
    fields_schema: [
      { key: 'artist', label: 'Artist', type: 'combobox' },
      { key: 'album', label: 'Album', type: 'combobox' },
      {
        key: 'genre',
        label: 'Genre',
        type: 'select',
        options: [
          'Rock',
          'Pop',
          'Hip-Hop',
          'R&B',
          'Jazz',
          'Classical',
          'Electronic',
          'Country',
          'Folk',
          'Metal',
          'Punk',
          'Blues',
          'Soul',
          'Reggae',
          'Latin',
          'World',
          'Indie',
          'Alternative',
          'Soundtrack',
          'Ambient',
        ],
      },
      {
        key: 'sub_genre',
        label: 'Sub-Genre',
        type: 'select',
        options: [
          'Prog Rock',
          'Classic Rock',
          'Indie Rock',
          'Post-Punk',
          'Synth-Pop',
          'K-Pop',
          'Trap',
          'Boom Bap',
          'Lo-Fi',
          'Neo-Soul',
          'Bebop',
          'Free Jazz',
          'Baroque',
          'Romantic',
          'House',
          'Techno',
          'Drum & Bass',
          'Bluegrass',
          'Americana',
          'Death Metal',
          'Black Metal',
          'Thrash Metal',
          'Post-Rock',
          'Shoegaze',
          'Dream Pop',
          'Grunge',
          'New Wave',
          'Hardcore Punk',
          'Metalcore',
          'Post-Hardcore',
          'Deathcore',
          'Screamo',
          'Melodic Hardcore',
          'Pop Punk',
          'Emo',
          'Crust Punk',
          'Sludge Metal',
          'Doom Metal',
          'Stoner Metal',
          'Crossover Thrash',
          'Power Violence',
          'Noise Rock',
          'Mathcore',
          'Skate Punk',
        ],
      },
      {
        key: 'format',
        label: 'Format',
        type: 'select',
        options: ['Vinyl', 'CD', 'Cassette', 'Digital'],
      },
      { key: 'label', label: 'Label', type: 'combobox' },
      { key: 'year_released', label: 'Year Released', type: 'number' },
      { key: 'track_count', label: 'Track Count', type: 'number' },
    ],
  },
  {
    key: 'movies',
    label: 'Movies',
    icon: '\uD83C\uDFAC',
    color: '#DC2626',
    sort_order: 3,
    fields_schema: [
      { key: 'director', label: 'Director', type: 'combobox' },
      {
        key: 'genre',
        label: 'Genre',
        type: 'select',
        options: [
          'Action',
          'Comedy',
          'Drama',
          'Horror',
          'Science Fiction',
          'Thriller',
          'Romance',
          'Animation',
          'Documentary',
          'Fantasy',
          'Mystery',
          'Crime',
          'Adventure',
          'War',
          'Western',
          'Musical',
          'Family',
          'Biographical',
        ],
      },
      {
        key: 'sub_genre',
        label: 'Sub-Genre',
        type: 'select',
        options: [
          'Slasher',
          'Psychological Horror',
          'Body Horror',
          'Found Footage',
          'Romantic Comedy',
          'Dark Comedy',
          'Heist',
          'Film Noir',
          'Superhero',
          'Martial Arts',
          'Disaster',
          'Spy',
          'Courtroom Drama',
          'Political Thriller',
          'Mockumentary',
          'Anime',
          'Stop Motion',
          'Coming of Age',
          'Period Drama',
          'Neo-Noir',
        ],
      },
      {
        key: 'format',
        label: 'Format',
        type: 'select',
        options: ['Blu-ray', 'DVD', '4K UHD', 'Digital'],
      },
      { key: 'runtime', label: 'Runtime (min)', type: 'number' },
      { key: 'year_released', label: 'Year Released', type: 'number' },
      { key: 'studio', label: 'Studio', type: 'combobox' },
      { key: 'cast', label: 'Cast', type: 'combobox' },
    ],
  },
  {
    key: 'tv',
    label: 'TV',
    icon: '\uD83D\uDCFA',
    color: '#2563EB',
    sort_order: 4,
    fields_schema: [
      { key: 'creator', label: 'Creator', type: 'combobox' },
      {
        key: 'genre',
        label: 'Genre',
        type: 'select',
        options: [
          'Drama',
          'Comedy',
          'Science Fiction',
          'Fantasy',
          'Crime',
          'Thriller',
          'Horror',
          'Documentary',
          'Reality',
          'Animation',
          'Anthology',
          'Limited Series',
        ],
      },
      {
        key: 'sub_genre',
        label: 'Sub-Genre',
        type: 'select',
        options: [
          'Sitcom',
          'Medical Drama',
          'Legal Drama',
          'Police Procedural',
          'Period Drama',
          'Dark Comedy',
          'Sketch Comedy',
          'True Crime',
          'Docuseries',
          'Anime',
          'Workplace Comedy',
          'Political Drama',
          'Space Opera',
          'Dystopian',
          'Supernatural',
          'Mystery',
          'Teen Drama',
          'Mockumentary',
        ],
      },
      {
        key: 'format',
        label: 'Format',
        type: 'select',
        options: ['Blu-ray', 'DVD', 'Digital'],
      },
      { key: 'seasons', label: 'Seasons', type: 'number' },
      { key: 'episodes', label: 'Episodes', type: 'number' },
      { key: 'network', label: 'Network', type: 'combobox' },
      { key: 'year_started', label: 'Year Started', type: 'number' },
      { key: 'year_ended', label: 'Year Ended', type: 'number' },
    ],
  },
  {
    key: 'games',
    label: 'Games',
    icon: '\uD83C\uDFAE',
    color: '#16A34A',
    sort_order: 5,
    fields_schema: [
      { key: 'developer', label: 'Developer', type: 'combobox' },
      { key: 'publisher', label: 'Publisher', type: 'combobox' },
      {
        key: 'platform',
        label: 'Platform',
        type: 'select',
        options: [
          'PC',
          'PlayStation 5',
          'PlayStation 4',
          'Xbox Series X|S',
          'Xbox One',
          'Nintendo Switch',
          'Nintendo 3DS',
          'PlayStation Vita',
          'Mobile',
          'Steam Deck',
        ],
      },
      {
        key: 'genre',
        label: 'Genre',
        type: 'select',
        options: [
          'Action',
          'Adventure',
          'RPG',
          'Strategy',
          'Simulation',
          'Sports',
          'Racing',
          'Puzzle',
          'Platformer',
          'Fighting',
          'Horror',
          'Shooter',
          'Sandbox',
          'MMO',
          'Visual Novel',
          'Rhythm',
        ],
      },
      {
        key: 'sub_genre',
        label: 'Sub-Genre',
        type: 'select',
        options: [
          'Action RPG',
          'Turn-Based RPG',
          'JRPG',
          'Metroidvania',
          'Roguelike',
          'Roguelite',
          'Battle Royale',
          'City Builder',
          'Tower Defense',
          'Survival Horror',
          'Stealth',
          'Open World',
          'Side-Scroller',
          'Tactical RPG',
          'Real-Time Strategy',
          'Turn-Based Strategy',
          'Hack and Slash',
          'Soulslike',
          'Card Game',
          'Party Game',
        ],
      },
      {
        key: 'format',
        label: 'Format',
        type: 'select',
        options: ['Physical', 'Digital'],
      },
      { key: 'year_released', label: 'Year Released', type: 'number' },
    ],
  },
]

export function seedBuiltinMediaTypes(db: Database.Database): void {
  const insert = db.prepare(`
    INSERT OR IGNORE INTO media_types (key, label, icon, color, fields_schema, is_builtin, sort_order)
    VALUES (@key, @label, @icon, @color, @fields_schema, 1, @sort_order)
  `)

  const seedAll = db.transaction(() => {
    for (const type of builtinMediaTypes) {
      insert.run({
        key: type.key,
        label: type.label,
        icon: type.icon,
        color: type.color,
        fields_schema: JSON.stringify(type.fields_schema),
        sort_order: type.sort_order,
      })
    }
  })

  seedAll()
}

export { builtinMediaTypes }
